uname(1)

# NAME

uname - print system information

# SYNOPSIS
*uname* [OPTIONS]

# OPTIONS


*-a*, *--all*
	Print all information, in the order -mnrsv

*-m*, *--machine*
	Print the machine hardware name

*-n*, *--nodename*
	Print the network node hostname

*-r*, *--kernel-release*
	Print the kernel release

*-s*, *--kernel-name*
	Print the kernel name

*-v*, *--kernel-version*
	Print the kernel version

*-h*, *--help*
	Show help message and quit

*-V*, *--version*
	Show version number and quit